rabbitmq:
  host: localhost
  port: 5672
  queue_name: image_prediction_queue
  durable: True
logging:
  level: INFO
db:
  user: appuser
  host: localhost
  port: 5432
  db_name: scoutcamservicedb
ml:
  gemma4_model_variation: gemma-4-e2b-it
